# Generated by Django 3.1.5 on 2021-01-31 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='prof',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.professor'),
        ),
        migrations.AddField(
            model_name='comment',
            name='stud',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.student'),
        ),
        migrations.AddField(
            model_name='comment',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='professor',
            name='dept',
            field=models.CharField(blank=True, choices=[('architecture', 'archi'), ('material-science-engineering', 'msc'), ('chemical-engineering', 'chemee'), ('chemistry', 'che'), ('civil-engineering', 'ce'), ('computer-science-engineering', 'cse'), ('electrical-engineering', 'ee'), ('electronics-communication-engineering', 'ece'), ('humanities-social-sciences', 'hs'), ('mathematics', 'math'), ('mechanical-engineering', 'mech'), ('physics', 'phy'), ('management-studies', 'man')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='designation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='portfolio_url',
            field=models.URLField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='rating',
            field=models.IntegerField(choices=[('worst', 0), ('bad', 1), ('ok', 2), ('nice', 3), ('good', 4), ('best', 5)], default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='karma',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
