# Generated by Django 3.1.5 on 2021-01-31 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210131_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='dept',
            field=models.CharField(blank=True, choices=[('archi', 'architecture'), ('msc', 'material-science-engineering'), ('chemee', 'chemical-engineering'), ('che', 'chemistry'), ('ce', 'civil-engineering'), ('cse', 'computer-science-engineering'), ('ee', 'electrical-engineering'), ('ece', 'electronics-communication-engineering'), ('hs', 'humanities-social-sciences'), ('math', 'mathematics'), ('mech', 'mechanical-engineering'), ('phy', 'physics'), ('man', 'management-studies')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='rating',
            field=models.IntegerField(choices=[(0, 'worst'), (1, 'bad'), (2, 'ok'), (3, 'nice'), (4, 'good'), (5, 'best')], default=0),
        ),
    ]
