# Generated by Django 3.1.5 on 2021-02-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_ratings_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratings',
            old_name='prof_if',
            new_name='prof_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='votes',
        ),
        migrations.AddField(
            model_name='upvotes',
            name='value',
            field=models.IntegerField(blank=True, choices=[(1, 'upvote'), (-1, 'downvote')], null=True),
        ),
    ]
