# Generated by Django 3.1.5 on 2021-02-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210204_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bio',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
