# Generated by Django 3.1.5 on 2021-04-21 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_student_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.student', unique=True),
        ),
    ]
